---

- hosts: nfs
  vars:
    disk_device: sdb
    nodes:
      - name: master
        ip: 192.168.188.6
      - name: worker1
        ip: 192.168.188.7
      - name: worker2
        ip: 192.168.188.5

  roles:
    - role: nfs-server

- hosts: nodes
  vars:
    nodes:
      - name: master
        ip: 192.168.188.6
    ports:
      - port: 6443/tcp
      - port: 2379-2380/tcp
      - port: 10250/tcp
      - port: 10251/tcp
      - port: 10252/tcp
      - port: 10255/tcp
  roles:
    - role: nodes

# OBSERVACIONES:
# - Mirar como podemos coger los ips de los nodos desde los inventarios
# (simplemente para no estar cambiando el inventario y este yml)